/**
 * Real Talk 4 – grocery item synonyms, shopkeeper option lines, Korean labels.
 * Keep in sync with src/realTalk4Mock.ts (MOCK_RT4_ITEM_WORDS, ITEM_OPTIONS, ITEM_KO_LABEL).
 */

export const RT4_ITEM_OPTS_EN = {
  apples: 'We have red apples and green apples. Which do you want?',
  milk: 'We have whole milk and skim milk. Which do you want?',
  bread: 'We have white bread and whole wheat. Which do you want?',
  eggs: 'We have large eggs and small eggs. Which do you want?',
  water: 'We have cold water and warm water. Which do you want?',
  juice: 'We have apple juice and orange juice. Which do you want?',
  bananas: 'We have yellow bananas and green bananas. Which do you want?',
  oranges: 'We have sweet oranges and sour oranges. Which do you want?',
  grapes: 'We have red grapes and green grapes. Which do you want?',
  fruits: 'We have apples, bananas, and oranges. Which do you want?',
  tomatoes: 'We have red tomatoes and yellow tomatoes. Which do you want?',
  potatoes: 'We have big potatoes and small potatoes. Which do you want?',
  carrots: 'We have baby carrots and long carrots. Which do you want?',
  onions: 'We have white onions and red onions. Which do you want?',
  lettuce: 'We have green lettuce and red lettuce. Which do you want?',
  cucumbers: 'We have long cucumbers and short cucumbers. Which do you want?',
  broccoli: 'We have big broccoli and small broccoli. Which do you want?',
  corn: 'We have sweet corn and plain corn. Which do you want?',
  spinach: 'We have baby spinach and big spinach. Which do you want?',
  peas: 'We have green peas and sweet peas. Which do you want?',
  strawberries: 'We have big strawberries and small strawberries. Which do you want?',
  watermelon: 'We have seedless watermelon and regular watermelon. Which do you want?',
  cheese: 'We have cheddar cheese and swiss cheese. Which do you want?',
  yogurt: 'We have plain yogurt and fruit yogurt. Which do you want?',
  butter: 'We have salted butter and unsalted butter. Which do you want?',
  chicken: 'We have chicken legs and chicken wings. Which do you want?',
  beef: 'We have ground beef and beef steak. Which do you want?',
  pork: 'We have pork chops and pork belly. Which do you want?',
  ham: 'We have sliced ham and thick ham. Which do you want?',
  bacon: 'We have thin bacon and thick bacon. Which do you want?',
  sausage: 'We have pork sausage and beef sausage. Which do you want?',
  fish: 'We have fresh fish and frozen fish. Which do you want?',
  shrimp: 'We have big shrimp and small shrimp. Which do you want?',
  rice: 'We have white rice and brown rice. Which do you want?',
  pasta: 'We have spaghetti and penne. Which do you want?',
  noodles: 'We have thin noodles and thick noodles. Which do you want?',
  cereal: 'We have corn flakes and oat rings. Which do you want?',
  chips: 'We have plain chips and cheese chips. Which do you want?',
  coffee: 'We have hot coffee and iced coffee. Which do you want?',
  tea: 'We have black tea and green tea. Which do you want?',
  pizza: 'We have cheese pizza and pepperoni pizza. Which do you want?',
  'ice cream': 'We have vanilla ice cream and chocolate ice cream. Which do you want?',
  soda: 'We have cola soda and lemon soda. Which do you want?',
  cake: 'We have chocolate cake and vanilla cake. Which do you want?',
  cookies: 'We have chocolate cookies and plain cookies. Which do you want?',
  donuts: 'We have glazed donuts and chocolate donuts. Which do you want?',
  muffins: 'We have blueberry muffins and plain muffins. Which do you want?',
  soup: 'We have chicken soup and tomato soup. Which do you want?',
  beans: 'We have black beans and red beans. Which do you want?',
  tuna: 'We have tuna in water and tuna in oil. Which do you want?',
  peanuts: 'We have salted peanuts and plain peanuts. Which do you want?',
  popcorn: 'We have butter popcorn and plain popcorn. Which do you want?',
  candy: 'We have sour candy and sweet candy. Which do you want?',
  chocolate: 'We have milk chocolate and dark chocolate. Which do you want?',
  lemons: 'We have big lemons and small lemons. Which do you want?',
  limes: 'We have big limes and small limes. Which do you want?',
  garlic: 'We have fresh garlic and peeled garlic. Which do you want?',
  mushrooms: 'We have white mushrooms and brown mushrooms. Which do you want?',
  cabbage: 'We have green cabbage and red cabbage. Which do you want?',
  tofu: 'We have soft tofu and firm tofu. Which do you want?',
  tortillas: 'We have corn tortillas and flour tortillas. Which do you want?',
  pickles: 'We have dill pickles and sweet pickles. Which do you want?',
  olives: 'We have green olives and black olives. Which do you want?',
  jam: 'We have strawberry jam and grape jam. Which do you want?',
  honey: 'We have light honey and dark honey. Which do you want?',
  flour: 'We have white flour and whole wheat flour. Which do you want?',
  sugar: 'We have white sugar and brown sugar. Which do you want?',
  salt: 'We have fine salt and coarse salt. Which do you want?',
  oil: 'We have olive oil and vegetable oil. Which do you want?',
  ketchup: 'We have regular ketchup and spicy ketchup. Which do you want?',
  mustard: 'We have yellow mustard and dijon mustard. Which do you want?',
  mayonnaise: 'We have regular mayo and light mayo. Which do you want?',
  crackers: 'We have plain crackers and cheese crackers. Which do you want?',
  croissants: 'We have butter croissants and chocolate croissants. Which do you want?',
  turkey: 'We have turkey slices and turkey legs. Which do you want?',
  beer: 'We have light beer and dark beer. Which do you want?',
  wine: 'We have red wine and white wine. Which do you want?',
  lemonade: 'We have pink lemonade and yellow lemonade. Which do you want?',
  'peanut butter': 'We have creamy peanut butter and crunchy peanut butter. Which do you want?',
  'soy milk': 'We have plain soy milk and vanilla soy milk. Which do you want?',
  'oat milk': 'We have plain oat milk and sweet oat milk. Which do you want?',
  'hot dogs': 'We have beef hot dogs and pork hot dogs. Which do you want?',
  blueberries: 'We have big blueberries and small blueberries. Which do you want?',
  cherries: 'We have red cherries and dark cherries. Which do you want?',
  peaches: 'We have yellow peaches and white peaches. Which do you want?',
  pears: 'We have green pears and red pears. Which do you want?',
  mangoes: 'We have ripe mangoes and firm mangoes. Which do you want?',
  kiwis: 'We have green kiwis and gold kiwis. Which do you want?',
  avocados: 'We have ripe avocados and firm avocados. Which do you want?',
  celery: 'We have celery sticks and celery hearts. Which do you want?',
  ginger: 'We have fresh ginger and ground ginger. Which do you want?',
  pretzels: 'We have salted pretzels and plain pretzels. Which do you want?',
  marshmallows: 'We have big marshmallows and mini marshmallows. Which do you want?',
  popsicles: 'We have fruit popsicles and cream popsicles. Which do you want?',
  smoothies: 'We have berry smoothies and banana smoothies. Which do you want?',
  cola: 'We have regular cola and zero cola. Which do you want?',
  almonds: 'We have roasted almonds and plain almonds. Which do you want?',
  nuts: 'We have mixed nuts and plain nuts. Which do you want?',
  jelly: 'We have grape jelly and strawberry jelly. Which do you want?',
  syrup: 'We have maple syrup and plain syrup. Which do you want?',
  bagels: 'We have plain bagels and sesame bagels. Which do you want?',
  buns: 'We have white buns and wheat buns. Which do you want?',
  pies: 'We have apple pie and cherry pie. Which do you want?',
  steak: 'We have thin steak and thick steak. Which do you want?',
  cream: 'We have heavy cream and light cream. Which do you want?',
  'rice cakes': 'We have plain rice cakes and cheese rice cakes. Which do you want?',
  pumpkins: 'We have big pumpkins and small pumpkins. Which do you want?',
  coconuts: 'We have whole coconuts and coconut pieces. Which do you want?',
  radishes: 'We have red radishes and white radishes. Which do you want?',
  beets: 'We have red beets and golden beets. Which do you want?',
  zucchini: 'We have green zucchini and yellow zucchini. Which do you want?',
  eggplant: 'We have big eggplant and small eggplant. Which do you want?',
  asparagus: 'We have thin asparagus and thick asparagus. Which do you want?',
  cauliflower: 'We have white cauliflower and orange cauliflower. Which do you want?',
  'green beans': 'We have long green beans and short green beans. Which do you want?',
  applesauce: 'We have sweet applesauce and plain applesauce. Which do you want?',
  oatmeal: 'We have plain oatmeal and maple oatmeal. Which do you want?',
  waffles: 'We have plain waffles and berry waffles. Which do you want?',
  pancakes: 'We have plain pancakes and chocolate pancakes. Which do you want?',
};

export const RT4_ITEM_OPTS_KO = {
  apples: '빨간 사과랑 초록 사과 있어. 어떤 거 할래?',
  milk: '통우유랑 저지방 우유 있어. 어떤 거 할래?',
  bread: '흰 빵이랑 통밀 빵 있어. 어떤 거 할래?',
  eggs: '큰 달걀이랑 작은 달걀 있어. 어떤 거 할래?',
  water: '찬 물이랑 따뜻한 물 있어. 어떤 거 할래?',
  juice: '사과 주스랑 오렌지 주스 있어. 어떤 거 할래?',
  bananas: '노란 바나나랑 초록 바나나 있어. 어떤 거 할래?',
  oranges: '달콤한 오렌지랑 새콤한 오렌지 있어. 어떤 거 할래?',
  grapes: '빨간 포도랑 초록 포도 있어. 어떤 거 할래?',
  fruits: '사과, 바나나, 오렌지 있어. 어떤 거 할래?',
  tomatoes: '빨간 토마토랑 노란 토마토 있어. 어떤 거 할래?',
  potatoes: '큰 감자랑 작은 감자 있어. 어떤 거 할래?',
  carrots: '아기 당근이랑 긴 당근 있어. 어떤 거 할래?',
  onions: '흰 양파랑 빨간 양파 있어. 어떤 거 할래?',
  lettuce: '초록 상추랑 빨간 상추 있어. 어떤 거 할래?',
  cucumbers: '긴 오이랑 짧은 오이 있어. 어떤 거 할래?',
  broccoli: '큰 브로콜리랑 작은 브로콜리 있어. 어떤 거 할래?',
  corn: '단맛 옥수수랑 일반 옥수수 있어. 어떤 거 할래?',
  spinach: '아기 시금치랑 큰 시금치 있어. 어떤 거 할래?',
  peas: '초록 완두랑 단맛 완두 있어. 어떤 거 할래?',
  strawberries: '큰 딸기랑 작은 딸기 있어. 어떤 거 할래?',
  watermelon: '씨 없는 수박이랑 일반 수박 있어. 어떤 거 할래?',
  cheese: '체다 치즈랑 스위스 치즈 있어. 어떤 거 할래?',
  yogurt: '플레인 요거트랑 과일 요거트 있어. 어떤 거 할래?',
  butter: '짠 버터랑 무염 버터 있어. 어떤 거 할래?',
  chicken: '닭다리랑 닭날개 있어. 어떤 거 할래?',
  beef: '다진 소고기랑 소고기 스테이크 있어. 어떤 거 할래?',
  pork: '돼지 갈비랑 삼겹살 있어. 어떤 거 할래?',
  ham: '얇게 썬 햄이랑 두꺼운 햄 있어. 어떤 거 할래?',
  bacon: '얇은 베이컨이랑 두꺼운 베이컨 있어. 어떤 거 할래?',
  sausage: '돼지 소시지랑 소고기 소시지 있어. 어떤 거 할래?',
  fish: '생선이랑 냉동 생선 있어. 어떤 거 할래?',
  shrimp: '큰 새우랑 작은 새우 있어. 어떤 거 할래?',
  rice: '흰쌀이랑 현미 있어. 어떤 거 할래?',
  pasta: '스파게티랑 펜네 있어. 어떤 거 할래?',
  noodles: '가는 국수랑 굵은 국수 있어. 어떤 거 할래?',
  cereal: '콘플레이크랑 오트링 있어. 어떤 거 할래?',
  chips: '플레인 칩이랑 치즈 칩 있어. 어떤 거 할래?',
  coffee: '따뜻한 커피랑 아이스 커피 있어. 어떤 거 할래?',
  tea: '홍차랑 녹차 있어. 어떤 거 할래?',
  pizza: '치즈 피자랑 페퍼로니 피자 있어. 어떤 거 할래?',
  'ice cream': '바닐라 아이스크림이랑 초콜릿 아이스크림 있어. 어떤 거 할래?',
  soda: '콜라 탄산이랑 레몬 탄산 있어. 어떤 거 할래?',
  cake: '초콜릿 케이크랑 바닐라 케이크 있어. 어떤 거 할래?',
  cookies: '초콜릿 쿠키랑 플레인 쿠키 있어. 어떤 거 할래?',
  donuts: '글레이즈 도넛이랑 초콜릿 도넛 있어. 어떤 거 할래?',
  muffins: '블루베리 머핀이랑 플레인 머핀 있어. 어떤 거 할래?',
  soup: '닭 수프랑 토마토 수프 있어. 어떤 거 할래?',
  beans: '검은콩이랑 빨간콩 있어. 어떤 거 할래?',
  tuna: '물에 넣은 참치랑 기름에 넣은 참치 있어. 어떤 거 할래?',
  peanuts: '짠 땅콩이랑 플레인 땅콩 있어. 어떤 거 할래?',
  popcorn: '버터 팝콘이랑 플레인 팝콘 있어. 어떤 거 할래?',
  candy: '새콤한 사탕이랑 단맛 사탕 있어. 어떤 거 할래?',
  chocolate: '밀크 초콜릿이랑 다크 초콜릿 있어. 어떤 거 할래?',
  lemons: '큰 레몬이랑 작은 레몬 있어. 어떤 거 할래?',
  limes: '큰 라임이랑 작은 라임 있어. 어떤 거 할래?',
  garlic: '통마늘이랑 깐 마늘 있어. 어떤 거 할래?',
  mushrooms: '흰 버섯이랑 갈색 버섯 있어. 어떤 거 할래?',
  cabbage: '초록 양배추랑 빨간 양배추 있어. 어떤 거 할래?',
  tofu: '부드러운 두부랑 단단한 두부 있어. 어떤 거 할래?',
  tortillas: '옥수수 또띠아랑 밀 또띠아 있어. 어떤 거 할래?',
  pickles: '딜 피클이랑 단맛 피클 있어. 어떤 거 할래?',
  olives: '초록 올리브랑 검은 올리브 있어. 어떤 거 할래?',
  jam: '딸기 잼이랑 포도 잼 있어. 어떤 거 할래?',
  honey: '밝은 꿀이랑 진한 꿀 있어. 어떤 거 할래?',
  flour: '흰 밀가루랑 통밀 밀가루 있어. 어떤 거 할래?',
  sugar: '흰 설탕이랑 흑설탕 있어. 어떤 거 할래?',
  salt: '고운 소금이랑 굵은 소금 있어. 어떤 거 할래?',
  oil: '올리브 오일이랑 식용유 있어. 어떤 거 할래?',
  ketchup: '일반 케첩이랑 매운 케첩 있어. 어떤 거 할래?',
  mustard: '옐로 머스타드랑 디종 머스타드 있어. 어떤 거 할래?',
  mayonnaise: '일반 마요랑 라이트 마요 있어. 어떤 거 할래?',
  crackers: '플레인 크래커랑 치즈 크래커 있어. 어떤 거 할래?',
  croissants: '버터 크루아상이랑 초콜릿 크루아상 있어. 어떤 거 할래?',
  turkey: '칠면조 슬라이스랑 칠면조 다리 있어. 어떤 거 할래?',
  beer: '라이트 맥주랑 다크 맥주 있어. 어떤 거 할래?',
  wine: '레드 와인이랑 화이트 와인 있어. 어떤 거 할래?',
  lemonade: '핑크 레모네이드랑 옐로 레모네이드 있어. 어떤 거 할래?',
  'peanut butter': '크리미 땅콩버터랑 크런치 땅콩버터 있어. 어떤 거 할래?',
  'soy milk': '플레인 두유랑 바닐라 두유 있어. 어떤 거 할래?',
  'oat milk': '플레인 오트밀크랑 단맛 오트밀크 있어. 어떤 거 할래?',
  'hot dogs': '소고기 핫도그랑 돼지고기 핫도그 있어. 어떤 거 할래?',
  blueberries: '큰 블루베리랑 작은 블루베리 있어. 어떤 거 할래?',
  cherries: '빨간 체리랑 진한 체리 있어. 어떤 거 할래?',
  peaches: '노란 복숭아랑 흰 복숭아 있어. 어떤 거 할래?',
  pears: '초록 배랑 빨간 배 있어. 어떤 거 할래?',
  mangoes: '익은 망고랑 단단한 망고 있어. 어떤 거 할래?',
  kiwis: '초록 키위랑 골드 키위 있어. 어떤 거 할래?',
  avocados: '익은 아보카도랑 단단한 아보카도 있어. 어떤 거 할래?',
  celery: '셀러리 스틱이랑 셀러리 하트 있어. 어떤 거 할래?',
  ginger: '생강 뿌리랑 생강 가루 있어. 어떤 거 할래?',
  pretzels: '짠 프레첼이랑 플레인 프레첼 있어. 어떤 거 할래?',
  marshmallows: '큰 마시멜로랑 미니 마시멜로 있어. 어떤 거 할래?',
  popsicles: '과일 아이스바랑 크림 아이스바 있어. 어떤 거 할래?',
  smoothies: '베리 스무디랑 바나나 스무디 있어. 어떤 거 할래?',
  cola: '일반 콜라랑 제로 콜라 있어. 어떤 거 할래?',
  almonds: '볶은 아몬드랑 플레인 아몬드 있어. 어떤 거 할래?',
  nuts: '믹스 넛츠랑 플레인 넛츠 있어. 어떤 거 할래?',
  jelly: '포도 젤리랑 딸기 젤리 있어. 어떤 거 할래?',
  syrup: '메이플 시럽이랑 일반 시럽 있어. 어떤 거 할래?',
  bagels: '플레인 베이글이랑 참깨 베이글 있어. 어떤 거 할래?',
  buns: '흰 번이랑 통밀 번 있어. 어떤 거 할래?',
  pies: '사과 파이랑 체리 파이 있어. 어떤 거 할래?',
  steak: '얇은 스테이크랑 두꺼운 스테이크 있어. 어떤 거 할래?',
  cream: '무거운 크림이랑 가벼운 크림 있어. 어떤 거 할래?',
  'rice cakes': '플레인 떡이랑 치즈 떡 있어. 어떤 거 할래?',
  pumpkins: '큰 호박이랑 작은 호박 있어. 어떤 거 할래?',
  coconuts: '통 코코넛이랑 코코넛 조각 있어. 어떤 거 할래?',
  radishes: '빨간 무랑 흰 무 있어. 어떤 거 할래?',
  beets: '빨간 비트랑 황금 비트 있어. 어떤 거 할래?',
  zucchini: '초록 주키니랑 노란 주키니 있어. 어떤 거 할래?',
  eggplant: '큰 가지랑 작은 가지 있어. 어떤 거 할래?',
  asparagus: '가는 아스파라거스랑 굵은 아스파라거스 있어. 어떤 거 할래?',
  cauliflower: '흰 콜리플라워랑 오렌지 콜리플라워 있어. 어떤 거 할래?',
  'green beans': '긴 콩이랑 짧은 콩 있어. 어떤 거 할래?',
  applesauce: '단맛 사과소스랑 플레인 사과소스 있어. 어떤 거 할래?',
  oatmeal: '플레인 오트밀이랑 메이플 오트밀 있어. 어떤 거 할래?',
  waffles: '플레인 와플이랑 베리 와플 있어. 어떤 거 할래?',
  pancakes: '플레인 팬케이크랑 초콜릿 팬케이크 있어. 어떤 거 할래?',
};
export const rt4ItemWordToCanonical = {
  "peanut butter": 'peanut butter',
  "spring onions": 'scallions',
  "whipped cream": 'whipped cream',
  strawberries: 'strawberries',
  marshmallows: 'marshmallows',
  peanutbutter: 'peanut butter',
  "string beans": 'green beans',
  cauliflowers: 'cauliflower',
  "green onions": 'scallions',
  "spring onion": 'scallions',
  "cream cheese": 'cream cheese',
  "rice noodles": 'rice noodles',
  "coconut milk": 'coconut milk',
  blueberries: 'blueberries',
  cauliflower: 'cauliflower',
  "green beans": 'green beans',
  marshmallow: 'marshmallows',
  "string bean": 'green beans',
  "green onion": 'scallions',
  "swiss chard": 'chard',
  watermelon: 'watermelon',
  mayonnaise: 'mayonnaise',
  croissants: 'croissants',
  "rice cakes": 'rice cakes',
  applesauce: 'applesauce',
  greenbeans: 'green beans',
  strawberry: 'strawberries',
  "green bean": 'green beans',
  cantaloupe: 'cantaloupe',
  "sour cream": 'sour cream',
  lemongrass: 'lemongrass',
  cucumbers: 'cucumbers',
  "ice cream": 'ice cream',
  chocolate: 'chocolate',
  mushrooms: 'mushrooms',
  tortillas: 'tortillas',
  popsicles: 'popsicles',
  smoothies: 'smoothies',
  asparagus: 'asparagus',
  ricecakes: 'rice cakes',
  blueberry: 'blueberries',
  croissant: 'croissants',
  doughnuts: 'donuts',
  zucchinis: 'zucchini',
  eggplants: 'eggplant',
  scallions: 'scallions',
  margarine: 'margarine',
  pepperoni: 'pepperoni',
  tomatoes: 'tomatoes',
  potatoes: 'potatoes',
  broccoli: 'broccoli',
  crackers: 'crackers',
  lemonade: 'lemonade',
  "soy milk": 'soy milk',
  "oat milk": 'oat milk',
  "hot dogs": 'hot dogs',
  cherries: 'cherries',
  avocados: 'avocados',
  pretzels: 'pretzels',
  pumpkins: 'pumpkins',
  coconuts: 'coconuts',
  radishes: 'radishes',
  zucchini: 'zucchini',
  eggplant: 'eggplant',
  pancakes: 'pancakes',
  icecream: 'ice cream',
  cucumber: 'cucumbers',
  mushroom: 'mushrooms',
  popsicle: 'popsicles',
  doughnut: 'donuts',
  scallion: 'scallions',
  cilantro: 'cilantro',
  couscous: 'couscous',
  bananas: 'bananas',
  oranges: 'oranges',
  carrots: 'carrots',
  lettuce: 'lettuce',
  spinach: 'spinach',
  chicken: 'chicken',
  sausage: 'sausage',
  noodles: 'noodles',
  cookies: 'cookies',
  muffins: 'muffins',
  peanuts: 'peanuts',
  popcorn: 'popcorn',
  cabbage: 'cabbage',
  pickles: 'pickles',
  ketchup: 'ketchup',
  mustard: 'mustard',
  peaches: 'peaches',
  mangoes: 'mangoes',
  almonds: 'almonds',
  oatmeal: 'oatmeal',
  waffles: 'waffles',
  soymilk: 'soy milk',
  oatmilk: 'oat milk',
  hotdogs: 'hot dogs',
  avocado: 'avocados',
  pretzel: 'pretzels',
  cracker: 'crackers',
  pumpkin: 'pumpkins',
  coconut: 'coconuts',
  pancake: 'pancakes',
  yoghurt: 'yogurt',
  "hot dog": 'hot dogs',
  parsley: 'parsley',
  raisins: 'raisins',
  arugula: 'arugula',
  turnips: 'turnips',
  apples: 'apples',
  grapes: 'grapes',
  fruits: 'fruits',
  onions: 'onions',
  cheese: 'cheese',
  yogurt: 'yogurt',
  butter: 'butter',
  shrimp: 'shrimp',
  cereal: 'cereal',
  coffee: 'coffee',
  donuts: 'donuts',
  lemons: 'lemons',
  garlic: 'garlic',
  olives: 'olives',
  turkey: 'turkey',
  celery: 'celery',
  ginger: 'ginger',
  bagels: 'bagels',
  banana: 'bananas',
  orange: 'oranges',
  tomato: 'tomatoes',
  potato: 'potatoes',
  carrot: 'carrots',
  pickle: 'pickles',
  cherry: 'cherries',
  almond: 'almonds',
  peanut: 'peanuts',
  muffin: 'muffins',
  cookie: 'cookies',
  noodle: 'noodles',
  radish: 'radishes',
  waffle: 'waffles',
  melons: 'melon',
  papaya: 'papaya',
  raisin: 'raisins',
  quinoa: 'quinoa',
  turnip: 'turnips',
  salami: 'salami',
  bread: 'bread',
  water: 'water',
  juice: 'juice',
  bacon: 'bacon',
  pasta: 'pasta',
  chips: 'chips',
  pizza: 'pizza',
  beans: 'beans',
  candy: 'candy',
  limes: 'limes',
  honey: 'honey',
  flour: 'flour',
  sugar: 'sugar',
  pears: 'pears',
  kiwis: 'kiwis',
  jelly: 'jelly',
  syrup: 'syrup',
  steak: 'steak',
  cream: 'cream',
  beets: 'beets',
  apple: 'apples',
  grape: 'grapes',
  onion: 'onions',
  lemon: 'lemons',
  olive: 'olives',
  peach: 'peaches',
  mango: 'mangoes',
  bagel: 'bagels',
  donut: 'donuts',
  fruit: 'fruits',
  leeks: 'leeks',
  melon: 'melon',
  dates: 'dates',
  basil: 'basil',
  chard: 'chard',
  milk: 'milk',
  eggs: 'eggs',
  corn: 'corn',
  peas: 'peas',
  beef: 'beef',
  pork: 'pork',
  fish: 'fish',
  rice: 'rice',
  soda: 'soda',
  cake: 'cake',
  soup: 'soup',
  tuna: 'tuna',
  tofu: 'tofu',
  salt: 'salt',
  beer: 'beer',
  wine: 'wine',
  cola: 'cola',
  nuts: 'nuts',
  buns: 'buns',
  pies: 'pies',
  lime: 'limes',
  pear: 'pears',
  kiwi: 'kiwis',
  bean: 'beans',
  beet: 'beets',
  chip: 'chips',
  mayo: 'mayonnaise',
  leek: 'leeks',
  kale: 'kale',
  date: 'dates',
  figs: 'figs',
  mint: 'mint',
  dill: 'dill',
  okra: 'okra',
  ham: 'ham',
  tea: 'tea',
  jam: 'jam',
  oil: 'oil',
  egg: 'eggs',
  pea: 'peas',
  bun: 'buns',
  pie: 'pies',
  pop: 'soda',
  fig: 'figs',
};

/** Korean short name for items not in RT4_ITEM_OPTS_* (generic "We have … Which do you want?"). */
export const RT4_ITEM_KO_LABEL = {
  leeks: '대파',
  scallions: '쪽파',
  kale: '케일',
  parsley: '파슬리',
  cilantro: '고수',
  melon: '멜론',
  cantaloupe: '멜론',
  papaya: '파파야',
  raisins: '건포도',
  dates: '대추야자',
  figs: '무화과',
  quinoa: '퀴노아',
  couscous: '쿠스쿠스',
  basil: '바질',
  mint: '민트',
  dill: '딜',
  'cream cheese': '크림치즈',
  'sour cream': '사워크림',
  margarine: '마가린',
  arugula: '루꼴라',
  chard: '스위스차드',
  okra: '오크라',
  turnips: '순무',
  lemongrass: '레몬그라스',
  'rice noodles': '쌀국수',
  'coconut milk': '코코넛 밀크',
  'whipped cream': '휘핑크림',
  pepperoni: '페퍼로니',
  salami: '살라미',
};

export function rt4PhraseEnForItem(itKey) {
  if (!itKey) return '';
  return RT4_ITEM_OPTS_EN[itKey] || `We have ${itKey}. Which do you want?`;
}

export function rt4PhraseKoForItem(itKey) {
  if (!itKey) return '';
  if (RT4_ITEM_OPTS_KO[itKey]) return RT4_ITEM_OPTS_KO[itKey];
  const lab = RT4_ITEM_KO_LABEL[itKey];
  if (lab) return `${lab} 있어. 어떤 거 할래?`;
  const t = itKey
    .split(' ')
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join(' ');
  return `${t} 있어. 어떤 거 할래?`;
}
